alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table Student drop constraint FKqs1bcxk3kl94mhxrur3v910fm
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists adr cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKct12qqt6r3xq0xl3w89qtfp4x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
